# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_structure.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget__left = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget__left.sizePolicy().hasHeightForWidth())
        self.tabWidget__left.setSizePolicy(sizePolicy)
        self.tabWidget__left.setObjectName("tabWidget__left")
        self.tab__displayx = QtWidgets.QWidget()
        self.tab__displayx.setObjectName("tab__displayx")
        self.tableWidget__displayx = QtWidgets.QTableWidget(self.tab__displayx)
        self.tableWidget__displayx.setGeometry(QtCore.QRect(10, 10, 151, 451))
        self.tableWidget__displayx.setObjectName("tableWidget__displayx")
        self.tableWidget__displayx.setColumnCount(0)
        self.tableWidget__displayx.setRowCount(0)
        self.tabWidget__left.addTab(self.tab__displayx, "")
        self.tab__displayu = QtWidgets.QWidget()
        self.tab__displayu.setObjectName("tab__displayu")
        self.tableWidget__displayu = QtWidgets.QTableWidget(self.tab__displayu)
        self.tableWidget__displayu.setGeometry(QtCore.QRect(10, 10, 271, 451))
        self.tableWidget__displayu.setObjectName("tableWidget__displayu")
        self.tableWidget__displayu.setColumnCount(0)
        self.tableWidget__displayu.setRowCount(0)
        self.tabWidget__left.addTab(self.tab__displayu, "")
        self.horizontalLayout_2.addWidget(self.tabWidget__left)
        self.tabWidget__right = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget__right.setObjectName("tabWidget__right")
        self.tab__displayGraph = QtWidgets.QWidget()
        self.tab__displayGraph.setObjectName("tab__displayGraph")
        self.widget__displayGraph = MplWidget(self.tab__displayGraph)
        self.widget__displayGraph.setGeometry(QtCore.QRect(10, 10, 541, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget__displayGraph.sizePolicy().hasHeightForWidth())
        self.widget__displayGraph.setSizePolicy(sizePolicy)
        self.widget__displayGraph.setObjectName("widget__displayGraph")
        self.tabWidget__right.addTab(self.tab__displayGraph, "")
        self.tab__displayConnProb = QtWidgets.QWidget()
        self.tab__displayConnProb.setObjectName("tab__displayConnProb")
        self.tableWidget__displayConnProb = QtWidgets.QTableWidget(self.tab__displayConnProb)
        self.tableWidget__displayConnProb.setGeometry(QtCore.QRect(10, 10, 541, 451))
        self.tableWidget__displayConnProb.setObjectName("tableWidget__displayConnProb")
        self.tableWidget__displayConnProb.setColumnCount(0)
        self.tableWidget__displayConnProb.setRowCount(0)
        self.tabWidget__right.addTab(self.tab__displayConnProb, "")
        self.tab__displayConnPower = QtWidgets.QWidget()
        self.tab__displayConnPower.setObjectName("tab__displayConnPower")
        self.tableWidget__displayConnPower = QtWidgets.QTableWidget(self.tab__displayConnPower)
        self.tableWidget__displayConnPower.setGeometry(QtCore.QRect(10, 10, 541, 451))
        self.tableWidget__displayConnPower.setObjectName("tableWidget__displayConnPower")
        self.tableWidget__displayConnPower.setColumnCount(0)
        self.tableWidget__displayConnPower.setRowCount(0)
        self.tabWidget__right.addTab(self.tab__displayConnPower, "")
        self.horizontalLayout_2.addWidget(self.tabWidget__right)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox__layoutSelect = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox__layoutSelect.setObjectName("comboBox__layoutSelect")
        self.horizontalLayout.addWidget(self.comboBox__layoutSelect)
        self.horizontalSlider__currentTime = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider__currentTime.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider__currentTime.setObjectName("horizontalSlider__currentTime")
        self.horizontalLayout.addWidget(self.horizontalSlider__currentTime)
        self.spinBox__currentTime = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox__currentTime.setMinimumSize(QtCore.QSize(30, 0))
        self.spinBox__currentTime.setObjectName("spinBox__currentTime")
        self.horizontalLayout.addWidget(self.spinBox__currentTime)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget__left.setCurrentIndex(0)
        self.tabWidget__right.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget__left.setTabText(self.tabWidget__left.indexOf(self.tab__displayx), _translate("MainWindow", "Координаты"))
        self.tabWidget__left.setTabText(self.tabWidget__left.indexOf(self.tab__displayu), _translate("MainWindow", "Управление"))
        self.tabWidget__right.setTabText(self.tabWidget__right.indexOf(self.tab__displayGraph), _translate("MainWindow", "Граф"))
        self.tabWidget__right.setTabText(self.tabWidget__right.indexOf(self.tab__displayConnProb), _translate("MainWindow", "Вероятности соединения"))
        self.tabWidget__right.setTabText(self.tabWidget__right.indexOf(self.tab__displayConnPower), _translate("MainWindow", "Силы соединения"))
from mplwidget import MplWidget
