# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget__inputMatrices = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget__inputMatrices.setGeometry(QtCore.QRect(20, 150, 361, 341))
        self.tabWidget__inputMatrices.setObjectName("tabWidget__inputMatrices")
        self.tab__x = QtWidgets.QWidget()
        self.tab__x.setObjectName("tab__x")
        self.tableWidget__inputx = QtWidgets.QTableWidget(self.tab__x)
        self.tableWidget__inputx.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputx.setObjectName("tableWidget__inputx")
        self.tableWidget__inputx.setColumnCount(0)
        self.tableWidget__inputx.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__x, "")
        self.tab__u = QtWidgets.QWidget()
        self.tab__u.setObjectName("tab__u")
        self.tableWidget__inputu = QtWidgets.QTableWidget(self.tab__u)
        self.tableWidget__inputu.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputu.setObjectName("tableWidget__inputu")
        self.tableWidget__inputu.setColumnCount(0)
        self.tableWidget__inputu.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__u, "")
        self.tab__A = QtWidgets.QWidget()
        self.tab__A.setObjectName("tab__A")
        self.tableWidget__inputA = QtWidgets.QTableWidget(self.tab__A)
        self.tableWidget__inputA.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputA.setObjectName("tableWidget__inputA")
        self.tableWidget__inputA.setColumnCount(0)
        self.tableWidget__inputA.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__A, "")
        self.tab__B = QtWidgets.QWidget()
        self.tab__B.setObjectName("tab__B")
        self.tableWidget__inputB = QtWidgets.QTableWidget(self.tab__B)
        self.tableWidget__inputB.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputB.setObjectName("tableWidget__inputB")
        self.tableWidget__inputB.setColumnCount(0)
        self.tableWidget__inputB.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__B, "")
        self.label__inputMatrices = QtWidgets.QLabel(self.centralwidget)
        self.label__inputMatrices.setGeometry(QtCore.QRect(20, 122, 351, 31))
        self.label__inputMatrices.setObjectName("label__inputMatrices")
        self.lineEdit__inputNodeAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit__inputNodeAmount.setGeometry(QtCore.QRect(150, 30, 113, 20))
        self.lineEdit__inputNodeAmount.setObjectName("lineEdit__inputNodeAmount")
        self.lineEdit__inputTime = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit__inputTime.setGeometry(QtCore.QRect(20, 30, 113, 20))
        self.lineEdit__inputTime.setObjectName("lineEdit__inputTime")
        self.label__inputTime = QtWidgets.QLabel(self.centralwidget)
        self.label__inputTime.setGeometry(QtCore.QRect(20, -1, 111, 31))
        self.label__inputTime.setObjectName("label__inputTime")
        self.label__inputNodeAmount = QtWidgets.QLabel(self.centralwidget)
        self.label__inputNodeAmount.setGeometry(QtCore.QRect(150, -1, 111, 31))
        self.label__inputNodeAmount.setObjectName("label__inputNodeAmount")
        self.label__inputMaxSubNodes = QtWidgets.QLabel(self.centralwidget)
        self.label__inputMaxSubNodes.setGeometry(QtCore.QRect(20, 490, 91, 41))
        self.label__inputMaxSubNodes.setObjectName("label__inputMaxSubNodes")
        self.lineEdit__inputMaxSubNodes = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit__inputMaxSubNodes.setGeometry(QtCore.QRect(20, 530, 113, 20))
        self.lineEdit__inputMaxSubNodes.setObjectName("lineEdit__inputMaxSubNodes")
        self.label__inputMaxTreeLength = QtWidgets.QLabel(self.centralwidget)
        self.label__inputMaxTreeLength.setGeometry(QtCore.QRect(150, 490, 121, 41))
        self.label__inputMaxTreeLength.setObjectName("label__inputMaxTreeLength")
        self.lineEdit__inputMaxTreeLength = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit__inputMaxTreeLength.setGeometry(QtCore.QRect(150, 530, 113, 20))
        self.lineEdit__inputMaxTreeLength.setObjectName("lineEdit__inputMaxTreeLength")
        self.checkBox__inputProbDepending = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox__inputProbDepending.setGeometry(QtCore.QRect(20, 556, 241, 21))
        self.checkBox__inputProbDepending.setObjectName("checkBox__inputProbDepending")
        self.pushButton__buildStructure = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__buildStructure.setGeometry(QtCore.QRect(20, 580, 361, 23))
        self.pushButton__buildStructure.setObjectName("pushButton__buildStructure")
        self.tabWidget__displayStructure = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget__displayStructure.setGeometry(QtCore.QRect(390, 10, 551, 551))
        self.tabWidget__displayStructure.setObjectName("tabWidget__displayStructure")
        self.tab__displayGraph = QtWidgets.QWidget()
        self.tab__displayGraph.setObjectName("tab__displayGraph")
        self.widget__displayGraph = MplWidget(self.tab__displayGraph)
        self.widget__displayGraph.setGeometry(QtCore.QRect(10, 10, 521, 501))
        self.widget__displayGraph.setObjectName("widget__displayGraph")
        self.tabWidget__displayStructure.addTab(self.tab__displayGraph, "")
        self.tab__displayProbMatrix = QtWidgets.QWidget()
        self.tab__displayProbMatrix.setObjectName("tab__displayProbMatrix")
        self.tableWidget__displayProbMatrix = QtWidgets.QTableWidget(self.tab__displayProbMatrix)
        self.tableWidget__displayProbMatrix.setGeometry(QtCore.QRect(10, 10, 521, 501))
        self.tableWidget__displayProbMatrix.setObjectName("tableWidget__displayProbMatrix")
        self.tableWidget__displayProbMatrix.setColumnCount(0)
        self.tableWidget__displayProbMatrix.setRowCount(0)
        self.tabWidget__displayStructure.addTab(self.tab__displayProbMatrix, "")
        self.tab__displayPowerMatrix = QtWidgets.QWidget()
        self.tab__displayPowerMatrix.setObjectName("tab__displayPowerMatrix")
        self.tableWidget__displayPowerMatrix = QtWidgets.QTableWidget(self.tab__displayPowerMatrix)
        self.tableWidget__displayPowerMatrix.setGeometry(QtCore.QRect(10, 10, 521, 501))
        self.tableWidget__displayPowerMatrix.setObjectName("tableWidget__displayPowerMatrix")
        self.tableWidget__displayPowerMatrix.setColumnCount(0)
        self.tableWidget__displayPowerMatrix.setRowCount(0)
        self.tabWidget__displayStructure.addTab(self.tab__displayPowerMatrix, "")
        self.horizontalSlider__controlTime = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider__controlTime.setGeometry(QtCore.QRect(390, 580, 491, 22))
        self.horizontalSlider__controlTime.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider__controlTime.setObjectName("horizontalSlider__controlTime")
        self.spinBox__controlTime = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox__controlTime.setGeometry(QtCore.QRect(890, 580, 51, 22))
        self.spinBox__controlTime.setObjectName("spinBox__controlTime")
        self.label__inputDistanceLinkOn = QtWidgets.QLabel(self.centralwidget)
        self.label__inputDistanceLinkOn.setGeometry(QtCore.QRect(20, 50, 111, 41))
        self.label__inputDistanceLinkOn.setObjectName("label__inputDistanceLinkOn")
        self.lineEdit__inputDistanceLinkOn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit__inputDistanceLinkOn.setGeometry(QtCore.QRect(20, 90, 113, 20))
        self.lineEdit__inputDistanceLinkOn.setObjectName("lineEdit__inputDistanceLinkOn")
        self.label__inputDistanceLinkOff = QtWidgets.QLabel(self.centralwidget)
        self.label__inputDistanceLinkOff.setGeometry(QtCore.QRect(150, 50, 111, 41))
        self.label__inputDistanceLinkOff.setObjectName("label__inputDistanceLinkOff")
        self.lineEdit__inputDistanceLinkOff = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit__inputDistanceLinkOff.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.lineEdit__inputDistanceLinkOff.setObjectName("lineEdit__inputDistanceLinkOff")
        self.pushButton__showProbFunc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__showProbFunc.setGeometry(QtCore.QRect(280, 30, 91, 81))
        self.pushButton__showProbFunc.setObjectName("pushButton__showProbFunc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget__inputMatrices.setCurrentIndex(0)
        self.tabWidget__displayStructure.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__x), _translate("MainWindow", "Координаты"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__u), _translate("MainWindow", "Управление"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__A), _translate("MainWindow", "A"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__B), _translate("MainWindow", "B"))
        self.label__inputMatrices.setText(_translate("MainWindow", "Матрицы"))
        self.label__inputTime.setText(_translate("MainWindow", "Время"))
        self.label__inputNodeAmount.setText(_translate("MainWindow", "Количество узлов"))
        self.label__inputMaxSubNodes.setText(_translate("MainWindow", "Макс. количество\n"
"дочерних узлов"))
        self.label__inputMaxTreeLength.setText(_translate("MainWindow", "Макс. глубина дерева"))
        self.checkBox__inputProbDepending.setText(_translate("MainWindow", "Вероятности узлов зависят друг от друга"))
        self.pushButton__buildStructure.setText(_translate("MainWindow", "Построить структуру"))
        self.tabWidget__displayStructure.setTabText(self.tabWidget__displayStructure.indexOf(self.tab__displayGraph), _translate("MainWindow", "Граф"))
        self.tabWidget__displayStructure.setTabText(self.tabWidget__displayStructure.indexOf(self.tab__displayProbMatrix), _translate("MainWindow", "Матрица вероятностей соединения"))
        self.tabWidget__displayStructure.setTabText(self.tabWidget__displayStructure.indexOf(self.tab__displayPowerMatrix), _translate("MainWindow", "Матрица сил соединения"))
        self.label__inputDistanceLinkOn.setText(_translate("MainWindow", "Расстояние\n"
"установки связи"))
        self.label__inputDistanceLinkOff.setText(_translate("MainWindow", "Расстояние\n"
"обрыва связи"))
        self.pushButton__showProbFunc.setText(_translate("MainWindow", "Функция\n"
"вероятности"))
from mplwidget import MplWidget
