# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(399, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout__description = QtWidgets.QVBoxLayout()
        self.verticalLayout__description.setObjectName("verticalLayout__description")
        self.label__nextNode = QtWidgets.QLabel(self.centralwidget)
        self.label__nextNode.setFrameShape(QtWidgets.QFrame.Box)
        self.label__nextNode.setAlignment(QtCore.Qt.AlignCenter)
        self.label__nextNode.setObjectName("label__nextNode")
        self.verticalLayout__description.addWidget(self.label__nextNode)
        self.verticalLayout_2.addLayout(self.verticalLayout__description)
        self.groupBox__params = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox__params.setObjectName("groupBox__params")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox__params)
        self.gridLayout.setObjectName("gridLayout")
        self.label__inputTime = QtWidgets.QLabel(self.groupBox__params)
        self.label__inputTime.setObjectName("label__inputTime")
        self.gridLayout.addWidget(self.label__inputTime, 0, 0, 1, 1)
        self.label__inputNodeAmount = QtWidgets.QLabel(self.groupBox__params)
        self.label__inputNodeAmount.setObjectName("label__inputNodeAmount")
        self.gridLayout.addWidget(self.label__inputNodeAmount, 0, 1, 1, 1)
        self.lineEdit__inputTime = QtWidgets.QLineEdit(self.groupBox__params)
        self.lineEdit__inputTime.setObjectName("lineEdit__inputTime")
        self.gridLayout.addWidget(self.lineEdit__inputTime, 1, 0, 1, 1)
        self.lineEdit__inputNodeAmount = QtWidgets.QLineEdit(self.groupBox__params)
        self.lineEdit__inputNodeAmount.setObjectName("lineEdit__inputNodeAmount")
        self.gridLayout.addWidget(self.lineEdit__inputNodeAmount, 1, 1, 1, 1)
        self.label__inputDistanceLinkOn = QtWidgets.QLabel(self.groupBox__params)
        self.label__inputDistanceLinkOn.setObjectName("label__inputDistanceLinkOn")
        self.gridLayout.addWidget(self.label__inputDistanceLinkOn, 2, 0, 1, 1)
        self.label__inputDistanceLinkOff = QtWidgets.QLabel(self.groupBox__params)
        self.label__inputDistanceLinkOff.setObjectName("label__inputDistanceLinkOff")
        self.gridLayout.addWidget(self.label__inputDistanceLinkOff, 2, 1, 1, 1)
        self.lineEdit__inputDistanceLinkOn = QtWidgets.QLineEdit(self.groupBox__params)
        self.lineEdit__inputDistanceLinkOn.setObjectName("lineEdit__inputDistanceLinkOn")
        self.gridLayout.addWidget(self.lineEdit__inputDistanceLinkOn, 3, 0, 1, 1)
        self.lineEdit__inputDistanceLinkOff = QtWidgets.QLineEdit(self.groupBox__params)
        self.lineEdit__inputDistanceLinkOff.setObjectName("lineEdit__inputDistanceLinkOff")
        self.gridLayout.addWidget(self.lineEdit__inputDistanceLinkOff, 3, 1, 1, 1)
        self.comboBox__smoothFunc = QtWidgets.QComboBox(self.groupBox__params)
        self.comboBox__smoothFunc.setObjectName("comboBox__smoothFunc")
        self.gridLayout.addWidget(self.comboBox__smoothFunc, 4, 0, 1, 1)
        self.pushButton__showProbFunc = QtWidgets.QPushButton(self.groupBox__params)
        self.pushButton__showProbFunc.setObjectName("pushButton__showProbFunc")
        self.gridLayout.addWidget(self.pushButton__showProbFunc, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox__params)
        self.groupBox__matrices = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox__matrices.setObjectName("groupBox__matrices")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox__matrices)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget__inputMatrices = QtWidgets.QTabWidget(self.groupBox__matrices)
        self.tabWidget__inputMatrices.setObjectName("tabWidget__inputMatrices")
        self.tab__x = QtWidgets.QWidget()
        self.tab__x.setObjectName("tab__x")
        self.tableWidget__inputx = QtWidgets.QTableWidget(self.tab__x)
        self.tableWidget__inputx.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputx.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget__inputx.setObjectName("tableWidget__inputx")
        self.tableWidget__inputx.setColumnCount(0)
        self.tableWidget__inputx.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__x, "")
        self.tab__u = QtWidgets.QWidget()
        self.tab__u.setObjectName("tab__u")
        self.tableWidget__inputu = QtWidgets.QTableWidget(self.tab__u)
        self.tableWidget__inputu.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputu.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget__inputu.setObjectName("tableWidget__inputu")
        self.tableWidget__inputu.setColumnCount(0)
        self.tableWidget__inputu.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__u, "")
        self.tab__A = QtWidgets.QWidget()
        self.tab__A.setObjectName("tab__A")
        self.tableWidget__inputA = QtWidgets.QTableWidget(self.tab__A)
        self.tableWidget__inputA.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputA.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget__inputA.setObjectName("tableWidget__inputA")
        self.tableWidget__inputA.setColumnCount(0)
        self.tableWidget__inputA.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__A, "")
        self.tab__B = QtWidgets.QWidget()
        self.tab__B.setObjectName("tab__B")
        self.tableWidget__inputB = QtWidgets.QTableWidget(self.tab__B)
        self.tableWidget__inputB.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.tableWidget__inputB.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget__inputB.setColumnCount(2)
        self.tableWidget__inputB.setObjectName("tableWidget__inputB")
        self.tableWidget__inputB.setRowCount(0)
        self.tabWidget__inputMatrices.addTab(self.tab__B, "")
        self.horizontalLayout_2.addWidget(self.tabWidget__inputMatrices)
        self.verticalLayout_2.addWidget(self.groupBox__matrices)
        self.groupBox__features = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox__features.setObjectName("groupBox__features")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox__features)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label__inputMaxSubNodes = QtWidgets.QLabel(self.groupBox__features)
        self.label__inputMaxSubNodes.setObjectName("label__inputMaxSubNodes")
        self.gridLayout_2.addWidget(self.label__inputMaxSubNodes, 0, 0, 1, 1)
        self.label__inputMaxTreeLength = QtWidgets.QLabel(self.groupBox__features)
        self.label__inputMaxTreeLength.setObjectName("label__inputMaxTreeLength")
        self.gridLayout_2.addWidget(self.label__inputMaxTreeLength, 0, 1, 1, 1)
        self.lineEdit__inputMaxSubNodes = QtWidgets.QLineEdit(self.groupBox__features)
        self.lineEdit__inputMaxSubNodes.setObjectName("lineEdit__inputMaxSubNodes")
        self.gridLayout_2.addWidget(self.lineEdit__inputMaxSubNodes, 1, 0, 1, 1)
        self.lineEdit__inputMaxTreeLength = QtWidgets.QLineEdit(self.groupBox__features)
        self.lineEdit__inputMaxTreeLength.setObjectName("lineEdit__inputMaxTreeLength")
        self.gridLayout_2.addWidget(self.lineEdit__inputMaxTreeLength, 1, 1, 1, 1)
        self.checkBox__inputProbDepending = QtWidgets.QCheckBox(self.groupBox__features)
        self.checkBox__inputProbDepending.setObjectName("checkBox__inputProbDepending")
        self.gridLayout_2.addWidget(self.checkBox__inputProbDepending, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox__features)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton__loadParams = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__loadParams.setObjectName("pushButton__loadParams")
        self.horizontalLayout.addWidget(self.pushButton__loadParams)
        self.pushButton__saveParams = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__saveParams.setObjectName("pushButton__saveParams")
        self.horizontalLayout.addWidget(self.pushButton__saveParams)
        self.pushButton__buildStructure = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__buildStructure.setObjectName("pushButton__buildStructure")
        self.horizontalLayout.addWidget(self.pushButton__buildStructure)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 399, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget__inputMatrices.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label__nextNode.setText(_translate("MainWindow", "Система"))
        self.groupBox__params.setTitle(_translate("MainWindow", "Параметры"))
        self.label__inputTime.setText(_translate("MainWindow", "Время"))
        self.label__inputNodeAmount.setText(_translate("MainWindow", "Количество узлов"))
        self.label__inputDistanceLinkOn.setText(_translate("MainWindow", "Расстояние\n"
"установки связи"))
        self.label__inputDistanceLinkOff.setText(_translate("MainWindow", "Расстояние\n"
"обрыва связи"))
        self.pushButton__showProbFunc.setText(_translate("MainWindow", "Функция вероятности"))
        self.groupBox__matrices.setTitle(_translate("MainWindow", "Матрицы"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__x), _translate("MainWindow", "Координаты"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__u), _translate("MainWindow", "Управление"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__A), _translate("MainWindow", "A"))
        self.tabWidget__inputMatrices.setTabText(self.tabWidget__inputMatrices.indexOf(self.tab__B), _translate("MainWindow", "B"))
        self.groupBox__features.setTitle(_translate("MainWindow", "Дополнительные возможности"))
        self.label__inputMaxSubNodes.setText(_translate("MainWindow", "Макс. количество\n"
"дочерних узлов"))
        self.label__inputMaxTreeLength.setText(_translate("MainWindow", "Макс. глубина дерева"))
        self.checkBox__inputProbDepending.setText(_translate("MainWindow", "Вероятности узлов зависят друг от друга"))
        self.pushButton__loadParams.setText(_translate("MainWindow", "Загрузить"))
        self.pushButton__saveParams.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton__buildStructure.setText(_translate("MainWindow", "Построить структуру"))
